themeColor = '#212121'
ogImage = 'https://URL/img/og/og-image.jpg'
touchIconSize = '180x180'
maskIconColor = '#1565c0'
tileColor = '#2d89ef'

[en]
title = 'Home'
titleTemplate = '''t => t ? `BoilerPlate | ${t}` : 'BoilerPlate' '''
description = ''
ogTitle = 'Home'
ogTemplate = '''t => `${t} - BoilerPlate.io`'''

[fr]
title = 'Accueil'
titleTemplate = '''t => t ? `BoilerPlate | ${t}` : 'BoilerPlate' '''
description = ''
ogTitle = 'Accueil'
ogTemplate = '''t => `${t} - BoilerPlate.io`'''

[[og]]
property = 'og:image:width'
content = ''
[[og]]
property = 'og:image:height'
content = ''
[[og]]
property = 'og:url'
content = 'https://URL'

[[tw]]
name = 'twitter:site'
content = '@'
[[tw]]
name = 'twitter:card'
content = 'summary_large_image'
[[tw]]
name = 'twitter:title'
content = 'BoilerPlate.io'
[[tw]]
name = 'twitter:creator'
content = '@hydreio'